### PR TITLE
Work around write chunk size for TLS streams for PHP < 7.1.4

### LINKED ISSUE #105: Error when sending large chunks of data over a secure TLS connection with older PHP versions
Originally reported here: https://github.com/reactphp/stream/issues/64

This can actually easily be reproduced by sending a "large" chunk of data at once over a TLS connection. On my system, this appears to be anything larger than around 30 KB at once passed to the underlying `fwrite()` call.

```
error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry
```

This is actually a bug in PHP that has been reported via https://bugs.php.net/bug.php?id=72333. The bug has been present for years and has been fixed recently via https://github.com/php/php-src/commit/17e9fc9bfeaf575b25782a42937a56e809155858 which landed in 7.1.4 and 7.0.18.

I've played around with different buffers and write chunks and it looks like this can be worked around by limiting the write chunk size to anything smaller than around 8 KB.

### PR DESCRIPTION
**Pull request by clue**
PHP < 7.1.4 (and PHP < 7.0.18) suffers from a bug when writing big chunks of data over TLS streams at once. We try to work around this by limiting the write chunk size to 8192 bytes for older PHP versions only. This is only a work-around and has a noticable performance penalty on affected versions. Please update your PHP version.

Closes / resolves #105

### CODE REVIEW

File: src/Connection.php [hunk 1]
```diff
@@ -50,20 +50,24 @@ public function __construct($resource, LoopInterface $loop)
...
+
+        // PHP < 7.1.14 (and PHP < 7.0.18) suffers from a bug when writing big
+        // chunks of data over TLS streams at once.
+        // We try to work around this by limiting the write chunk size to 8192
+        // bytes for older PHP versions only.
+        // This is only a work-around and has a noticable performance penalty on
+        // affected versions. Please update your PHP version.
+        // This applies to all streams because TLS may be enabled later on.
+        // See https://github.com/reactphp/socket/issues/105
+        $limitWriteChunks = (PHP_VERSION_ID < 70018 || (PHP_VERSION_ID < 70114 && PHP_VERSION_ID >= 70100));
```
Comment (kelunik) [inline src/Connection.php]: That should be `PHP_VERSION_ID >= 70100 && PHP_VERSION_ID < 70114` for better readability IMO.

Comment (clue) [reply src/Connection.php]: Unfortunately this does not match the same version range. The fix landed in PHP 7.1.14 *and* PHP 7.0.18, which means that all earlier versions are affected (such as 7.1.13 and 7.0.17, but *not* 7.0.19)

Comment (kelunik) [reply src/Connection.php]: Yes, sure, just talking about the second condition being switched.

`PHP_VERSION_ID < 70018 || PHP_VERSION_ID >= 70100 && PHP_VERSION_ID < 70114`

Comment (clue) [reply src/Connection.php]: I don't think either version is any clearer, so I've just updated this to match your suggestion :shipit: :+1:

**Comment by clue** [comment]
Wait a moment, typo'd the version, this has been fixed in PHP 7.1.4, not PHP 7.1.14…

**Comment by clue** [comment]
Sorry for the confusion, PR updated to reference affected PHP < 7.1.4 now :shipit: 

See also https://github.com/reactphp/socket/issues/105 and https://github.com/php/php-src/commit/17e9fc9bfeaf575b25782a42937a56e809155858

**Comment by WyriHaximus** [comment]
:shipit:
